#SPDX-License-Identifier: MIT
#Copyright (c) "2023" . The DeepCausality Authors. All Rights Reserved.

name: Tests

on: [ pull_request, push ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose

      - name: Run Doc tests
        run: cargo test --doc --verbose

      - name: Run tests
        run: cargo test --verbose